### PR TITLE
Donation page improvements

### PR DESCRIPTION
**Pull request by binarymaster**
- Avoid payment details overflow the columns
- Allow to copy payment details as text into clipboard

I tested this on my 1024x600 monitor, but it should look good on higher resolutions too.

---

## BEFORE
image

---

## AFTER
image

### CODE REVIEW

**Comment by ColinFinck** [comment]
Just looked at the images for now, but I like the idea! :)
I'm wondering about two things though:

- Can we show a "Copy" button only when the mouse moves into the respective edit field? Otherwise, the page looks a bit cluttered with buttons.
- Could we assign the same size to the "IBAN" and "BIC/SWIFT code" fields, so that both buttons are aligned?

**Comment by learn-more** [comment]
@ColinFinck not sure how strict we want to be here wrt nicks?
the commit was made with a nick instead of a full name.

**Comment by ColinFinck** [comment]
I think nicknames are fine for the website.

**Comment by ColinFinck** [comment]
I've just added you to the "Trusted Web-Playground Users" and your PRs to web-content are now automatically built and made available at *.web-content.reactos.org.
That said, your changes look great at https://pr15.web-content.reactos.org. Time to merge!

**Comment by learn-more** [comment]
https://i.imgur.com/IktxzxI.png

**Comment by ColinFinck** [comment]
> https://i.imgur.com/IktxzxI.png

@learn-more: Yep, this is something else we need to fix.
As I already said, I would like the new website to be fully self-contained and not depend on external services. That goes together with maintaining the privacy of our visitors. Which easily helps with GDPR compliance without requiring a long cookie disclaimer :)

Therefore, I have set up a strict Content-Security-Policy in the web server. Everything that still depends on external sources now needs to be made locally available.
For Yandex, the <iframe> needs to be replaced by a button or link to their donation page.
Liberapay hasn't really took off after over a year, and booking minor donations creates more hassle than profit, so we should remove it entirely for now.

The remaining 6 donations options should then be arranged in a 2-column format (instead of the current 3-column format) to make the entire page look less overwhelming.

This may all sound like a lot of efforts for a single page, but this page is actually giving us measurable income :)

**Pull request merged**
