### PR TITLE
Add a news item about our website launch

### PR DESCRIPTION
**Pull request by ColinFinck**
I plan to launch the new ReactOS website on 2020-03-21, and this is the announcement I have written for the launch.
I invite the core ReactOS Team, contributors to the new website, and native English speakers to have a look at my announcement, and confirm it or suggest changes. This PR shall also serve as a first example on how we can collaborate on website content in the future :)

### CODE REVIEW

**Comment by ColinFinck** [comment]
This is how it looks rendered: https://pr33.web-content.reactos.org/project-news/the-new-reactos-website/

GitHub doesn't let me add each and every person as a reviewer to this PR, and I'm pretty sure you don't want that either. Therefore, please just comment or self-request a review if you are having a look.

**Comment by foxlet** [comment]
I don't think the website is particularly ready, considering broken mobile rendering and oddities with scrolling.

**Comment by binarymaster** [comment]
@foxlet I reported scrolling problem as [ONLINE-885](https://jira.reactos.org/browse/ONLINE-885). Please report mobile rendering problems you encountered with detailed descriptions.

**Comment by ColinFinck** [comment]
> I don't think the website is completely ready, considering broken mobile rendering and oddities with scrolling.

I'm only aware of minor glitches on mobile, which still makes it much better than our current website.
I don't consider them blockers for the launch. And we haven't attracted people to fix these in 2 years, so there is no point in postponing the launch even further.

It will be the same as with every other product launch: Most bugs will only be reported and fixed after the launch, because only a very small number of people is actually participating in the beta test.
Won't surprise me if exactly that is going to happen again :)

**Pull request merged**
