### PR TITLE
Add the Discord icon badge and link in the footer

### PR DESCRIPTION
**Pull request by Fraizeraust**
Also upgrade FontAwesome to version 5.13.1. The said upgrade is necessary in order to have Discord icon badge present.

### CODE REVIEW

**Comment by Fraizeraust** [comment]
Colin told me it's fine as it is (I had a discussion with him before I started working on this which he allowed me to do so). Unless many of you want me to split the commit then I'll do it.

**Comment by ColinFinck** [comment]
> This should be probably done in two separate commits.

As adding the Discord icon is just one more obvious line on top of the FontAwesome 5 upgrade, I didn't really care whether it was done in 1 or 2 commits.
Both is readable to the average reviewer, and getting things done is better than getting things perfect.

**Comment by ColinFinck** [comment]
I had a look at https://pr70.web-content.reactos.org/ and I'm surprised to see that so much spacing is gone.
Has FontAwesome officially changed the icon spacing in version 5?

After we have found a convincing explanation, I would like to see the previous spacing restored. If FontAwesome has reduced the spacing, we need to add it back using CSS.
Currently, icons in the bottom right corner look squashed (compare with https://reactos.org/) and the colorful background when hovering an icon is hardly visible.

Also, did they really remove the "blank" calendar icon we are using for news entries right now and only left the "filled" one you are using now?
I would like to see no change in this regard if possible

**Comment by Fraizeraust** [comment]
> I had a look at https://pr70.web-content.reactos.org/ and I'm surprised to see that so much spacing is gone.
Has FontAwesome officially changed the icon spacing in version 5?

The 4 and 5 version of FontAwesome are entirely different in terms of design and internals now (as per their article, they say FontAwesome 5 is written from scratch). So that means many things have changed, as well as icons and icon spacing as well.

https://fontawesome.com/v5.9.0/how-to-use/on-the-web/setup/upgrading-from-version-4

Regarding the calendar icon, the blank one (calendar-o) is also removed with the new upgrade. I'll see what I can do with icon spacing and colour background of them in CSS but I can't promise much for everything else.

**Comment by Extravert-ir** [comment]
Is there a point in upgrading to FontAwesome 5? Are we lacking some icons which are not present in 4.7?

**Comment by ColinFinck** [comment]
> Is there a point in upgrading to FontAwesome 5? Are we lacking some icons which are not present in 4.7?

Yes, the Discord icon added here

**Pull request merged**
